category: IT Services
commonfields:
  id: Kubernetes
  version: -1
configuration:
- display: Cluster host URL (e.g. https://api.us-east-2.starter.openshift-online.com:6443)
  name: cluster_host_url
  required: true
  type: 0
- display: Authentication token
  name: auth_token
  required: true
  type: 4
- display: Cluster namespace
  name: namspace
  required: true
  type: 0  
description: |-
  Kubernetes integration for managing and scanning clusters for security vulnerabilities. 
display: Kubernetes
name: Kubernetes
script:
  commands:
    deprecated: false
    description: List pods in cluster.
    execution: false
    name: k8s-list-pods
    outputs:
    - contextPath: Kubernetes.Pods.Name
      description: Name
      type: String
    - contextPath: Kubernetes.Pods.Status
      description: Status
      type: String
    - contextPath: Kubernetes.Pods.Containers
      description: Containers
      type: Number
    - contextPath: Kubernetes.Pods.Ready
      description: Ready
      type: Number
    - contextPath: Kubernetes.Pods.Restarts
      description: Restarts
      type: Number
    - contextPath: Kubernetes.Pods.Started
      description: Started
      type: Date
    - contextPath: Kubernetes.Pods.Age
      description: Age
      type: String
  dockerimage: demisto/python3:3.8.5.10845
  isfetch: true
  longRunning: false
  longRunningPort: false
  runonce: false
  script: '-'
  subtype: python3
  type: python
defaultclassifier: HelloWorld
defaultmapperin: HelloWorld-mapper
fromversion: 5.0.0
